name: 'Notify'
description: 'Notify Slack for CI builds'
inputs:
  slack_webhook:
    description: "Full URL of the Slack webhook"
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/notify.sh
      shell: bash
      env:
        COMMIT_AUTHOR: ${{ github.event.pusher.name }}
        COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
        SLACK_WEBHOOK: ${{ inputs.slack_webhook }}
