name: Diff Contains
description: Return true if we find a search team in a git diff
inputs:
  search:
    description: A word to search for
    required: true
outputs:
  result:
    description: Returns true or false as strings
    value: ${{ steps.contains.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: contains
      shell: bash
      run: ${{ github.action_path }}/run.sh
      env:
        SEARCH_TERM: ${{ inputs.search }}
        DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
