name: Diff Contains
description: Return true if we find a search team in a git diff
inputs:
  search:
    description: A word to search for
    required: true
outputs:
  result:
    description: Returns true or false as strings
    value: ${{ steps.contains.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: contains
      shell: bash
      run: |
        set -xe

        git fetch origin ${{ github.event.repository.default_branch }} --depth=1
        export DIFF=$(git diff -i -S${{ inputs.search }} --name-only origin/${{ github.event.repository.default_branch }} $GITHUB_SHA)

        RESULT=false
        if [[ $DIFF != "" ]]; then
          echo -e "$DIFF"

          RESULT=true
        fi

        echo ::set-output name=result::$RESULT
